#!/bin/bash
#cd CALCS
#for vlm in {10 20 30 40 50 60 70 80 90}
echo "TEST OF LETTERS"
echo "   VLM  |  LYR   "
for VLM in 10 50 100 200
do
    for((LYR = 26; LYR <= 266; LYR++))
        do
        echo "   $VLM   |   $LYR   "
        ./predictor $LYR $VLM
        done
done
echo "done!!!"
